import type { ViewContext } from './types.js';

export type DefineViewProps<T extends ViewContext = ViewContext> = T;

export interface ComponentPropDefinition {
  name: string;
  required: boolean;
  defaultValue?: unknown;
  tsType: string;
}

export class ViewPropsValidationError extends Error {
  constructor(
    readonly viewName: string,
    readonly missing: string[],
  ) {
    super(
      `Missing required view props for [${viewName}]: ${missing.join(', ')}`,
    );
    this.name = 'ViewPropsValidationError';
  }
}

export function parsePropsSchema(
  props: Record<string, unknown>,
): ComponentPropDefinition[] {
  return Object.entries(props).map(([name, defaultValue]) => ({
    name,
    required: defaultValue === undefined,
    defaultValue,
    tsType: inferTypeScriptType(defaultValue),
  }));
}

export function validateViewProps(
  props: Record<string, unknown>,
  context: ViewContext,
  viewName: string,
): void {
  const missing: string[] = [];

  for (const [name, defaultValue] of Object.entries(props)) {
    if (defaultValue !== undefined) {
      continue;
    }

    const value = context[name];
    if (value === undefined || value === null) {
      missing.push(name);
    }
  }

  if (missing.length > 0) {
    throw new ViewPropsValidationError(viewName, missing);
  }
}

export function generateViewPropsMapInterface(
  entries: Record<string, Record<string, unknown>>,
): string {
  const lines = ['interface ViewPropsMap {'];

  for (const [viewName, props] of Object.entries(entries).sort(([left], [right]) =>
    left.localeCompare(right),
  )) {
    const schema = parsePropsSchema(props);
    if (schema.length === 0) {
      continue;
    }

    const fields = schema
      .map((prop) => {
        const optional = prop.required ? '' : '?';
        return `    ${JSON.stringify(prop.name)}${optional}: ${prop.tsType};`;
      })
      .join('\n');

    lines.push(`  ${JSON.stringify(viewName)}: {`);
    lines.push(fields);
    lines.push('  };');
  }

  lines.push('}');
  return lines.join('\n');
}

export function generateViewPropsDeclarationFile(
  entries: Record<string, Record<string, unknown>>,
): string {
  const body = generateViewPropsMapInterface(entries);
  const hasEntries = body.includes(': {');

  if (!hasEntries) {
    return [
      '// Generated by `pondoknusa view:types`. Do not edit manually.',
      '',
      'export {};',
      '',
    ].join('\n');
  }

  return [
    '// Generated by `pondoknusa view:types`. Do not edit manually.',
    '',
    "declare module '@pondoknusa/views' {",
    body,
    '}',
    '',
    'export {};',
    '',
  ].join('\n');
}

function inferTypeScriptType(value: unknown): string {
  if (value === undefined) {
    return 'unknown';
  }

  if (value === null) {
    return 'null';
  }

  switch (typeof value) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    default:
      return 'unknown';
  }
}