[build]
builder = "DOCKERFILE"
dockerfilePath = "deploy/Dockerfile"

[deploy]
preDeployCommand = "npx pondoknusa migrate"
startCommand = "./deploy/docker-entrypoint.sh"
healthcheckPath = "/health/ready"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"