// Generated by scripts/generate-docs.mjs — package links refresh on docs:generate.

export const guideSidebar = [
  {
    text: 'Getting started',
    items: [
      { text: 'Introduction', link: '/guide/introduction' },
      { text: 'Installation', link: '/guide/getting-started' },
      { text: 'Application structure', link: '/guide/application-structure' },
      { text: 'API stability', link: '/guide/api-stability' },
      { text: 'Upgrading to 1.0', link: '/guide/upgrading-to-1.0' },
      { text: 'Configuration reference', link: '/guide/configuration-reference' },
    ],
  },
  {
    text: 'Deployment',
    items: [
      { text: 'Overview', link: '/guide/deployment' },
      { text: 'Docker', link: '/guide/deployment/docker' },
      { text: 'Fly.io', link: '/guide/deployment/fly' },
      { text: 'Railway', link: '/guide/deployment/railway' },
    ],
  },
  {
    text: 'Core concepts',
    items: [
      { text: 'Configuration', link: '/guide/configuration' },
      { text: 'Routing', link: '/guide/routing' },
      { text: 'Controllers & middleware', link: '/guide/controllers' },
      { text: 'Validation & form requests', link: '/guide/validation' },
    ],
  },
  {
    text: 'Data & APIs',
    items: [
      { text: 'Database & ORM', link: '/guide/database' },
      { text: 'API resources', link: '/guide/api-resources' },
      { text: 'Pagination', link: '/guide/pagination' },
    ],
  },
  {
    text: 'Platform features',
    items: [
      { text: 'Authentication', link: '/guide/auth' },
      { text: 'Post-quantum crypto', link: '/guide/crypto' },
      { text: 'Cache', link: '/guide/cache' },
      { text: 'Mail', link: '/guide/mail' },
      { text: 'Notifications', link: '/guide/notifications' },
      { text: 'Storage', link: '/guide/storage' },
      { text: 'Queues & jobs', link: '/guide/queues' },
      { text: 'Events', link: '/guide/events' },
      { text: 'Broadcasting', link: '/guide/broadcasting' },
      { text: 'Views & templating', link: '/guide/views' },
      { text: 'Testing', link: '/guide/testing' },
    ],
  },
  {
    text: 'Packages',
    items: [
      { text: 'Service container', link: '/guide/container' },
      { text: 'Collections', link: '/guide/collection' },
      { text: 'Support utilities', link: '/guide/support' },
      { text: 'Ecosystem', link: '/guide/ecosystem' },
    ],
  },
];

export const referenceSidebar = [
  {
    "text": "Overview",
    "link": "/reference/"
  },
  {
    "text": "All packages",
    "link": "/reference/generated/packages"
  },
  {
    "text": "CLI commands",
    "link": "/reference/generated/cli"
  },
  {
    "text": "Facades",
    "link": "/reference/generated/facades"
  },
  {
    "text": "AI & agents",
    "collapsed": true,
    "items": [
      {
        "text": "graphql",
        "link": "/reference/generated/packages/graphql"
      },
      {
        "text": "mcp",
        "link": "/reference/generated/packages/mcp"
      },
      {
        "text": "rag",
        "link": "/reference/generated/packages/rag"
      },
      {
        "text": "vector",
        "link": "/reference/generated/packages/vector"
      },
      {
        "text": "vector-pg",
        "link": "/reference/generated/packages/vector-pg"
      },
      {
        "text": "vector-pinecone",
        "link": "/reference/generated/packages/vector-pinecone"
      },
      {
        "text": "vector-qdrant",
        "link": "/reference/generated/packages/vector-qdrant"
      }
    ]
  },
  {
    "text": "Cache drivers",
    "collapsed": true,
    "items": [
      {
        "text": "cache-dynamodb",
        "link": "/reference/generated/packages/cache-dynamodb"
      },
      {
        "text": "cache-memcached",
        "link": "/reference/generated/packages/cache-memcached"
      },
      {
        "text": "cache-upstash",
        "link": "/reference/generated/packages/cache-upstash"
      }
    ]
  },
  {
    "text": "Database",
    "collapsed": true,
    "items": [
      {
        "text": "database",
        "link": "/reference/generated/packages/database"
      },
      {
        "text": "database-mysql",
        "link": "/reference/generated/packages/database-mysql"
      },
      {
        "text": "database-pg",
        "link": "/reference/generated/packages/database-pg"
      }
    ]
  },
  {
    "text": "Developer experience",
    "collapsed": true,
    "items": [
      {
        "text": "cli",
        "link": "/reference/generated/packages/cli"
      },
      {
        "text": "testing",
        "link": "/reference/generated/packages/testing"
      }
    ]
  },
  {
    "text": "Kernel & HTTP",
    "collapsed": true,
    "items": [
      {
        "text": "collection",
        "link": "/reference/generated/packages/collection"
      },
      {
        "text": "config",
        "link": "/reference/generated/packages/config"
      },
      {
        "text": "container",
        "link": "/reference/generated/packages/container"
      },
      {
        "text": "core",
        "link": "/reference/generated/packages/core"
      },
      {
        "text": "http",
        "link": "/reference/generated/packages/http"
      },
      {
        "text": "support",
        "link": "/reference/generated/packages/support"
      },
      {
        "text": "validation",
        "link": "/reference/generated/packages/validation"
      }
    ]
  },
  {
    "text": "Platform services",
    "collapsed": true,
    "items": [
      {
        "text": "admin",
        "link": "/reference/generated/packages/admin"
      },
      {
        "text": "auth",
        "link": "/reference/generated/packages/auth"
      },
      {
        "text": "auth-oauth",
        "link": "/reference/generated/packages/auth-oauth"
      },
      {
        "text": "broadcasting",
        "link": "/reference/generated/packages/broadcasting"
      },
      {
        "text": "broadcasting-websocket",
        "link": "/reference/generated/packages/broadcasting-websocket"
      },
      {
        "text": "cache",
        "link": "/reference/generated/packages/cache"
      },
      {
        "text": "crypto",
        "link": "/reference/generated/packages/crypto"
      },
      {
        "text": "debug",
        "link": "/reference/generated/packages/debug"
      },
      {
        "text": "events",
        "link": "/reference/generated/packages/events"
      },
      {
        "text": "log",
        "link": "/reference/generated/packages/log"
      },
      {
        "text": "mail",
        "link": "/reference/generated/packages/mail"
      },
      {
        "text": "notifications",
        "link": "/reference/generated/packages/notifications"
      },
      {
        "text": "queue",
        "link": "/reference/generated/packages/queue"
      },
      {
        "text": "repl",
        "link": "/reference/generated/packages/repl"
      },
      {
        "text": "storage",
        "link": "/reference/generated/packages/storage"
      }
    ]
  },
  {
    "text": "Redis",
    "collapsed": true,
    "items": [
      {
        "text": "redis",
        "link": "/reference/generated/packages/redis"
      },
      {
        "text": "redis-node",
        "link": "/reference/generated/packages/redis-node"
      }
    ]
  },
  {
    "text": "Storage drivers",
    "collapsed": true,
    "items": [
      {
        "text": "storage-aws-s3",
        "link": "/reference/generated/packages/storage-aws-s3"
      },
      {
        "text": "storage-r2",
        "link": "/reference/generated/packages/storage-r2"
      },
      {
        "text": "storage-supabase",
        "link": "/reference/generated/packages/storage-supabase"
      }
    ]
  },
  {
    "text": "Views & client",
    "collapsed": true,
    "items": [
      {
        "text": "echo",
        "link": "/reference/generated/packages/echo"
      },
      {
        "text": "locale",
        "link": "/reference/generated/packages/locale"
      },
      {
        "text": "ssr",
        "link": "/reference/generated/packages/ssr"
      },
      {
        "text": "views",
        "link": "/reference/generated/packages/views"
      }
    ]
  }
];

export const tutorialsSidebar = [
  {
    text: 'Tutorial track',
    items: [
      { text: 'Overview', link: '/tutorials/' },
      { text: '1. Install & first route', link: '/tutorials/01-install-and-first-route' },
      { text: '2. Auth & database', link: '/tutorials/02-auth-and-database' },
      { text: '3. Queues & events', link: '/tutorials/03-queues-and-events' },
      { text: '4. Realtime & deploy', link: '/tutorials/04-realtime-and-deploy' },
    ],
  },
];

export const cookbookSidebar = [
  {
    text: 'Recipes',
    items: [
      { text: 'Overview', link: '/cookbook/' },
      { text: 'Realtime UI with Echo', link: '/cookbook/realtime-echo' },
      { text: 'RAG Q&A endpoint', link: '/cookbook/rag-q-and-a' },
      { text: 'Testing with fakes', link: '/cookbook/testing-fakes' },
      { text: 'Admin panel', link: '/cookbook/admin-panel' },
      { text: 'Multi-locale apps', link: '/cookbook/multi-locale' },
    ],
  },
];
