export interface RouteListEntry {
  method: string;
  uri: string;
  name?: string;
  middleware: string[];
  action: string;
}

export interface OpenApiExportOptions {
  title?: string;
  version?: string;
  serverUrl?: string;
}

function openApiPath(pattern: string): string {
  if (!pattern.startsWith('/')) {
    return `/${pattern}`;
  }
  return pattern.replace(/:([A-Za-z0-9_]+)/g, '{$1}');
}

function inferTag(path: string): string {
  const segments = path.split('/').filter(Boolean);
  if (segments[0] === 'api' && segments[1]) {
    return segments[1];
  }
  return segments[0] ?? 'default';
}

export function routesToOpenApi(
  routes: RouteListEntry[],
  options: OpenApiExportOptions = {},
): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};

  for (const route of routes) {
    const path = openApiPath(route.uri);
    const method = route.method.toLowerCase();
    const tag = inferTag(path);

    if (!paths[path]) {
      paths[path] = {};
    }

    paths[path][method] = {
      summary: route.name ?? route.action,
      operationId: route.name ?? `${route.method}_${path.replace(/[{}/]/g, '_')}`,
      tags: [tag],
      ...(route.middleware.length > 0
        ? { description: `Middleware: ${route.middleware.join(', ')}` }
        : {}),
      responses: {
        '200': { description: 'Successful response' },
        '401': { description: 'Unauthenticated' },
        '422': { description: 'Validation error' },
      },
    };
  }

  return {
    openapi: '3.0.3',
    info: {
      title: options.title ?? 'Pondoknusa API',
      version: options.version ?? '1.0.0',
      description:
        'Generated by `pondoknusa make:openapi`. Refine schemas and request bodies in storage/api/openapi.json.',
    },
    servers: [{ url: options.serverUrl ?? 'http://127.0.0.1:3000' }],
    paths,
  };
}