import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import { describe, expect, it } from 'vitest';

const ROOT = join(import.meta.dirname, '..');

describe('generate-docs', () => {
  it('generates package, CLI, and manifest reference outputs', () => {
    execSync('node scripts/generate-docs.mjs', { cwd: ROOT, stdio: 'pipe' });

    const packagesOverview = join(ROOT, 'docs/reference/generated/packages.md');
    const cliReference = join(ROOT, 'docs/reference/generated/cli.md');
    const corePackage = join(ROOT, 'docs/reference/generated/packages/core.md');
    const manifest = join(ROOT, 'docs/.vitepress/generated/manifest.json');
    const sidebar = join(ROOT, 'docs/.vitepress/sidebar.mts');

    expect(existsSync(packagesOverview)).toBe(true);
    expect(existsSync(cliReference)).toBe(true);
    expect(existsSync(corePackage)).toBe(true);
    expect(existsSync(manifest)).toBe(true);
    expect(existsSync(sidebar)).toBe(true);

    const packagesDoc = readFileSync(packagesOverview, 'utf8');
    expect(packagesDoc).toContain('@pondoknusa/core');
    expect(packagesDoc).toContain('Generated by scripts/generate-docs.mjs');

    const cliDoc = readFileSync(cliReference, 'utf8');
    expect(cliDoc).toContain('`migrate`');
    expect(cliDoc).toContain('| `new` |');

    const coreDoc = readFileSync(corePackage, 'utf8');
    expect(coreDoc).toContain('## Public exports');
    expect(coreDoc).toContain('`Route`');

    const parsedManifest = JSON.parse(readFileSync(manifest, 'utf8')) as {
      packages: Array<{ name: string }>;
      commands: string[];
    };
    expect(parsedManifest.packages.length).toBeGreaterThan(40);
    expect(parsedManifest.commands).toContain('migrate');
    expect(parsedManifest.commands).toContain('view:catalog');
  });
});